// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'entitys.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `from_display_info`, `print_debug_log`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LddKeyboardManager>>
abstract class LddKeyboardManager implements RustOpaqueInterface {
  ///读取键盘类型的设备信息
  List<LddKeyboard> getLddKeyboardList();

  ///监听梁典典键盘数据
  /// [gun_device] - 扫码枪设备，如果不传，则不判断
  Stream<LddRawEvent> listenLddKeyboardEvent({LddKeyboard? gunDevice});

  factory LddKeyboardManager({bool? printDebug, bool? gunAddEndReturnKey}) =>
      RustLib.instance.api.crateApiMultiinputLddKeyboardManagerNew(
          printDebug: printDebug, gunAddEndReturnKey: gunAddEndReturnKey);

  ///注册键盘监听
  void register();
}
