// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.3.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -2110124214;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__api__keyboard_listen__start_listen_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_listen",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::syste::LddKeyboardValue,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::keyboard_listen::start_listen(api_sink);
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__syste__start_listen_system_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_listen_system_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::syste::LddEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, String>((move || {
                    let output_ok = crate::api::syste::start_listen_system_event(api_sink)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__crate__api__syste__start_listen_systen_event_by_ldd_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "start_listen_systen_event_by_ldd",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::syste::LddKeyboardValue,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            let api_millis = <Option<u64>>::sse_decode(&mut deserializer);
            let api_min_size = <Option<usize>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::api::syste::start_listen_systen_event_by_ldd(
                            api_sink,
                            api_millis,
                            api_min_size,
                        );
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<crate::api::syste::LddEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::syste::LddKeyboardValue,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for u128 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return inner.parse().unwrap();
    }
}

impl SseDecode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_f64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for crate::api::syste::LddButton {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::syste::LddButton::Left;
            }
            1 => {
                return crate::api::syste::LddButton::Right;
            }
            2 => {
                return crate::api::syste::LddButton::Middle;
            }
            3 => {
                let mut var_field0 = <u8>::sse_decode(deserializer);
                return crate::api::syste::LddButton::Unknown(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::syste::LddEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_eventType = <crate::api::syste::LddEventType>::sse_decode(deserializer);
        return crate::api::syste::LddEvent {
            name: var_name,
            event_type: var_eventType,
        };
    }
}

impl SseDecode for crate::api::syste::LddEventType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <crate::api::syste::LddKey>::sse_decode(deserializer);
                return crate::api::syste::LddEventType::KeyPress(var_field0);
            }
            1 => {
                let mut var_field0 = <crate::api::syste::LddKey>::sse_decode(deserializer);
                return crate::api::syste::LddEventType::KeyRelease(var_field0);
            }
            2 => {
                let mut var_field0 = <crate::api::syste::LddButton>::sse_decode(deserializer);
                return crate::api::syste::LddEventType::ButtonPress(var_field0);
            }
            3 => {
                let mut var_field0 = <crate::api::syste::LddButton>::sse_decode(deserializer);
                return crate::api::syste::LddEventType::ButtonRelease(var_field0);
            }
            4 => {
                let mut var_x = <f64>::sse_decode(deserializer);
                let mut var_y = <f64>::sse_decode(deserializer);
                return crate::api::syste::LddEventType::MouseMove { x: var_x, y: var_y };
            }
            5 => {
                let mut var_deltaX = <i64>::sse_decode(deserializer);
                let mut var_deltaY = <i64>::sse_decode(deserializer);
                return crate::api::syste::LddEventType::Wheel {
                    delta_x: var_deltaX,
                    delta_y: var_deltaY,
                };
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::syste::LddKey {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                return crate::api::syste::LddKey::Alt;
            }
            1 => {
                return crate::api::syste::LddKey::AltGr;
            }
            2 => {
                return crate::api::syste::LddKey::Backspace;
            }
            3 => {
                return crate::api::syste::LddKey::CapsLock;
            }
            4 => {
                return crate::api::syste::LddKey::ControlLeft;
            }
            5 => {
                return crate::api::syste::LddKey::ControlRight;
            }
            6 => {
                return crate::api::syste::LddKey::Delete;
            }
            7 => {
                return crate::api::syste::LddKey::DownArrow;
            }
            8 => {
                return crate::api::syste::LddKey::End;
            }
            9 => {
                return crate::api::syste::LddKey::Escape;
            }
            10 => {
                return crate::api::syste::LddKey::F1;
            }
            11 => {
                return crate::api::syste::LddKey::F10;
            }
            12 => {
                return crate::api::syste::LddKey::F11;
            }
            13 => {
                return crate::api::syste::LddKey::F12;
            }
            14 => {
                return crate::api::syste::LddKey::F2;
            }
            15 => {
                return crate::api::syste::LddKey::F3;
            }
            16 => {
                return crate::api::syste::LddKey::F4;
            }
            17 => {
                return crate::api::syste::LddKey::F5;
            }
            18 => {
                return crate::api::syste::LddKey::F6;
            }
            19 => {
                return crate::api::syste::LddKey::F7;
            }
            20 => {
                return crate::api::syste::LddKey::F8;
            }
            21 => {
                return crate::api::syste::LddKey::F9;
            }
            22 => {
                return crate::api::syste::LddKey::Home;
            }
            23 => {
                return crate::api::syste::LddKey::LeftArrow;
            }
            24 => {
                return crate::api::syste::LddKey::MetaLeft;
            }
            25 => {
                return crate::api::syste::LddKey::MetaRight;
            }
            26 => {
                return crate::api::syste::LddKey::PageDown;
            }
            27 => {
                return crate::api::syste::LddKey::PageUp;
            }
            28 => {
                return crate::api::syste::LddKey::Return;
            }
            29 => {
                return crate::api::syste::LddKey::RightArrow;
            }
            30 => {
                return crate::api::syste::LddKey::ShiftLeft;
            }
            31 => {
                return crate::api::syste::LddKey::ShiftRight;
            }
            32 => {
                return crate::api::syste::LddKey::Space;
            }
            33 => {
                return crate::api::syste::LddKey::Tab;
            }
            34 => {
                return crate::api::syste::LddKey::UpArrow;
            }
            35 => {
                return crate::api::syste::LddKey::PrintScreen;
            }
            36 => {
                return crate::api::syste::LddKey::ScrollLock;
            }
            37 => {
                return crate::api::syste::LddKey::Pause;
            }
            38 => {
                return crate::api::syste::LddKey::NumLock;
            }
            39 => {
                return crate::api::syste::LddKey::BackQuote;
            }
            40 => {
                return crate::api::syste::LddKey::Num1;
            }
            41 => {
                return crate::api::syste::LddKey::Num2;
            }
            42 => {
                return crate::api::syste::LddKey::Num3;
            }
            43 => {
                return crate::api::syste::LddKey::Num4;
            }
            44 => {
                return crate::api::syste::LddKey::Num5;
            }
            45 => {
                return crate::api::syste::LddKey::Num6;
            }
            46 => {
                return crate::api::syste::LddKey::Num7;
            }
            47 => {
                return crate::api::syste::LddKey::Num8;
            }
            48 => {
                return crate::api::syste::LddKey::Num9;
            }
            49 => {
                return crate::api::syste::LddKey::Num0;
            }
            50 => {
                return crate::api::syste::LddKey::Minus;
            }
            51 => {
                return crate::api::syste::LddKey::Equal;
            }
            52 => {
                return crate::api::syste::LddKey::KeyQ;
            }
            53 => {
                return crate::api::syste::LddKey::KeyW;
            }
            54 => {
                return crate::api::syste::LddKey::KeyE;
            }
            55 => {
                return crate::api::syste::LddKey::KeyR;
            }
            56 => {
                return crate::api::syste::LddKey::KeyT;
            }
            57 => {
                return crate::api::syste::LddKey::KeyY;
            }
            58 => {
                return crate::api::syste::LddKey::KeyU;
            }
            59 => {
                return crate::api::syste::LddKey::KeyI;
            }
            60 => {
                return crate::api::syste::LddKey::KeyO;
            }
            61 => {
                return crate::api::syste::LddKey::KeyP;
            }
            62 => {
                return crate::api::syste::LddKey::LeftBracket;
            }
            63 => {
                return crate::api::syste::LddKey::RightBracket;
            }
            64 => {
                return crate::api::syste::LddKey::KeyA;
            }
            65 => {
                return crate::api::syste::LddKey::KeyS;
            }
            66 => {
                return crate::api::syste::LddKey::KeyD;
            }
            67 => {
                return crate::api::syste::LddKey::KeyF;
            }
            68 => {
                return crate::api::syste::LddKey::KeyG;
            }
            69 => {
                return crate::api::syste::LddKey::KeyH;
            }
            70 => {
                return crate::api::syste::LddKey::KeyJ;
            }
            71 => {
                return crate::api::syste::LddKey::KeyK;
            }
            72 => {
                return crate::api::syste::LddKey::KeyL;
            }
            73 => {
                return crate::api::syste::LddKey::SemiColon;
            }
            74 => {
                return crate::api::syste::LddKey::Quote;
            }
            75 => {
                return crate::api::syste::LddKey::BackSlash;
            }
            76 => {
                return crate::api::syste::LddKey::IntlBackslash;
            }
            77 => {
                return crate::api::syste::LddKey::KeyZ;
            }
            78 => {
                return crate::api::syste::LddKey::KeyX;
            }
            79 => {
                return crate::api::syste::LddKey::KeyC;
            }
            80 => {
                return crate::api::syste::LddKey::KeyV;
            }
            81 => {
                return crate::api::syste::LddKey::KeyB;
            }
            82 => {
                return crate::api::syste::LddKey::KeyN;
            }
            83 => {
                return crate::api::syste::LddKey::KeyM;
            }
            84 => {
                return crate::api::syste::LddKey::Comma;
            }
            85 => {
                return crate::api::syste::LddKey::Dot;
            }
            86 => {
                return crate::api::syste::LddKey::Slash;
            }
            87 => {
                return crate::api::syste::LddKey::Insert;
            }
            88 => {
                return crate::api::syste::LddKey::KpReturn;
            }
            89 => {
                return crate::api::syste::LddKey::KpMinus;
            }
            90 => {
                return crate::api::syste::LddKey::KpPlus;
            }
            91 => {
                return crate::api::syste::LddKey::KpMultiply;
            }
            92 => {
                return crate::api::syste::LddKey::KpDivide;
            }
            93 => {
                return crate::api::syste::LddKey::Kp0;
            }
            94 => {
                return crate::api::syste::LddKey::Kp1;
            }
            95 => {
                return crate::api::syste::LddKey::Kp2;
            }
            96 => {
                return crate::api::syste::LddKey::Kp3;
            }
            97 => {
                return crate::api::syste::LddKey::Kp4;
            }
            98 => {
                return crate::api::syste::LddKey::Kp5;
            }
            99 => {
                return crate::api::syste::LddKey::Kp6;
            }
            100 => {
                return crate::api::syste::LddKey::Kp7;
            }
            101 => {
                return crate::api::syste::LddKey::Kp8;
            }
            102 => {
                return crate::api::syste::LddKey::Kp9;
            }
            103 => {
                return crate::api::syste::LddKey::KpDelete;
            }
            104 => {
                return crate::api::syste::LddKey::Function;
            }
            105 => {
                let mut var_field0 = <u32>::sse_decode(deserializer);
                return crate::api::syste::LddKey::Unknown(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for crate::api::syste::LddKeyboardValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut tag_ = <i32>::sse_decode(deserializer);
        match tag_ {
            0 => {
                let mut var_field0 = <String>::sse_decode(deserializer);
                let mut var_field1 = <u128>::sse_decode(deserializer);
                return crate::api::syste::LddKeyboardValue::ScanGunValue(var_field0, var_field1);
            }
            1 => {
                let mut var_field0 = <crate::api::syste::LddEvent>::sse_decode(deserializer);
                let mut var_field1 = <u128>::sse_decode(deserializer);
                return crate::api::syste::LddKeyboardValue::KeyboardValue(var_field0, var_field1);
            }
            2 => {
                let mut var_field0 = <Vec<crate::api::syste::LddEvent>>::sse_decode(deserializer);
                return crate::api::syste::LddKeyboardValue::ScanGunValueV2(var_field0);
            }
            3 => {
                let mut var_field0 = <crate::api::syste::LddEvent>::sse_decode(deserializer);
                return crate::api::syste::LddKeyboardValue::KeyboardValueV2(var_field0);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseDecode for Vec<crate::api::syste::LddEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::syste::LddEvent>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<usize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<usize>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => {
            wire__crate__api__keyboard_listen__start_listen_impl(port, ptr, rust_vec_len, data_len)
        }
        2 => wire__crate__api__syste__start_listen_system_event_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        3 => wire__crate__api__syste__start_listen_systen_event_by_ldd_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::syste::LddButton {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::syste::LddButton::Left => [0.into_dart()].into_dart(),
            crate::api::syste::LddButton::Right => [1.into_dart()].into_dart(),
            crate::api::syste::LddButton::Middle => [2.into_dart()].into_dart(),
            crate::api::syste::LddButton::Unknown(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::syste::LddButton {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::syste::LddButton>
    for crate::api::syste::LddButton
{
    fn into_into_dart(self) -> crate::api::syste::LddButton {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::syste::LddEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.name.into_into_dart().into_dart(),
            self.event_type.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::syste::LddEvent {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::syste::LddEvent>
    for crate::api::syste::LddEvent
{
    fn into_into_dart(self) -> crate::api::syste::LddEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::syste::LddEventType {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::syste::LddEventType::KeyPress(field0) => {
                [0.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::syste::LddEventType::KeyRelease(field0) => {
                [1.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::syste::LddEventType::ButtonPress(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::syste::LddEventType::ButtonRelease(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::syste::LddEventType::MouseMove { x, y } => [
                4.into_dart(),
                x.into_into_dart().into_dart(),
                y.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::syste::LddEventType::Wheel { delta_x, delta_y } => [
                5.into_dart(),
                delta_x.into_into_dart().into_dart(),
                delta_y.into_into_dart().into_dart(),
            ]
            .into_dart(),
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::syste::LddEventType
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::syste::LddEventType>
    for crate::api::syste::LddEventType
{
    fn into_into_dart(self) -> crate::api::syste::LddEventType {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::syste::LddKey {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::syste::LddKey::Alt => [0.into_dart()].into_dart(),
            crate::api::syste::LddKey::AltGr => [1.into_dart()].into_dart(),
            crate::api::syste::LddKey::Backspace => [2.into_dart()].into_dart(),
            crate::api::syste::LddKey::CapsLock => [3.into_dart()].into_dart(),
            crate::api::syste::LddKey::ControlLeft => [4.into_dart()].into_dart(),
            crate::api::syste::LddKey::ControlRight => [5.into_dart()].into_dart(),
            crate::api::syste::LddKey::Delete => [6.into_dart()].into_dart(),
            crate::api::syste::LddKey::DownArrow => [7.into_dart()].into_dart(),
            crate::api::syste::LddKey::End => [8.into_dart()].into_dart(),
            crate::api::syste::LddKey::Escape => [9.into_dart()].into_dart(),
            crate::api::syste::LddKey::F1 => [10.into_dart()].into_dart(),
            crate::api::syste::LddKey::F10 => [11.into_dart()].into_dart(),
            crate::api::syste::LddKey::F11 => [12.into_dart()].into_dart(),
            crate::api::syste::LddKey::F12 => [13.into_dart()].into_dart(),
            crate::api::syste::LddKey::F2 => [14.into_dart()].into_dart(),
            crate::api::syste::LddKey::F3 => [15.into_dart()].into_dart(),
            crate::api::syste::LddKey::F4 => [16.into_dart()].into_dart(),
            crate::api::syste::LddKey::F5 => [17.into_dart()].into_dart(),
            crate::api::syste::LddKey::F6 => [18.into_dart()].into_dart(),
            crate::api::syste::LddKey::F7 => [19.into_dart()].into_dart(),
            crate::api::syste::LddKey::F8 => [20.into_dart()].into_dart(),
            crate::api::syste::LddKey::F9 => [21.into_dart()].into_dart(),
            crate::api::syste::LddKey::Home => [22.into_dart()].into_dart(),
            crate::api::syste::LddKey::LeftArrow => [23.into_dart()].into_dart(),
            crate::api::syste::LddKey::MetaLeft => [24.into_dart()].into_dart(),
            crate::api::syste::LddKey::MetaRight => [25.into_dart()].into_dart(),
            crate::api::syste::LddKey::PageDown => [26.into_dart()].into_dart(),
            crate::api::syste::LddKey::PageUp => [27.into_dart()].into_dart(),
            crate::api::syste::LddKey::Return => [28.into_dart()].into_dart(),
            crate::api::syste::LddKey::RightArrow => [29.into_dart()].into_dart(),
            crate::api::syste::LddKey::ShiftLeft => [30.into_dart()].into_dart(),
            crate::api::syste::LddKey::ShiftRight => [31.into_dart()].into_dart(),
            crate::api::syste::LddKey::Space => [32.into_dart()].into_dart(),
            crate::api::syste::LddKey::Tab => [33.into_dart()].into_dart(),
            crate::api::syste::LddKey::UpArrow => [34.into_dart()].into_dart(),
            crate::api::syste::LddKey::PrintScreen => [35.into_dart()].into_dart(),
            crate::api::syste::LddKey::ScrollLock => [36.into_dart()].into_dart(),
            crate::api::syste::LddKey::Pause => [37.into_dart()].into_dart(),
            crate::api::syste::LddKey::NumLock => [38.into_dart()].into_dart(),
            crate::api::syste::LddKey::BackQuote => [39.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num1 => [40.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num2 => [41.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num3 => [42.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num4 => [43.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num5 => [44.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num6 => [45.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num7 => [46.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num8 => [47.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num9 => [48.into_dart()].into_dart(),
            crate::api::syste::LddKey::Num0 => [49.into_dart()].into_dart(),
            crate::api::syste::LddKey::Minus => [50.into_dart()].into_dart(),
            crate::api::syste::LddKey::Equal => [51.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyQ => [52.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyW => [53.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyE => [54.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyR => [55.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyT => [56.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyY => [57.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyU => [58.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyI => [59.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyO => [60.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyP => [61.into_dart()].into_dart(),
            crate::api::syste::LddKey::LeftBracket => [62.into_dart()].into_dart(),
            crate::api::syste::LddKey::RightBracket => [63.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyA => [64.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyS => [65.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyD => [66.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyF => [67.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyG => [68.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyH => [69.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyJ => [70.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyK => [71.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyL => [72.into_dart()].into_dart(),
            crate::api::syste::LddKey::SemiColon => [73.into_dart()].into_dart(),
            crate::api::syste::LddKey::Quote => [74.into_dart()].into_dart(),
            crate::api::syste::LddKey::BackSlash => [75.into_dart()].into_dart(),
            crate::api::syste::LddKey::IntlBackslash => [76.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyZ => [77.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyX => [78.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyC => [79.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyV => [80.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyB => [81.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyN => [82.into_dart()].into_dart(),
            crate::api::syste::LddKey::KeyM => [83.into_dart()].into_dart(),
            crate::api::syste::LddKey::Comma => [84.into_dart()].into_dart(),
            crate::api::syste::LddKey::Dot => [85.into_dart()].into_dart(),
            crate::api::syste::LddKey::Slash => [86.into_dart()].into_dart(),
            crate::api::syste::LddKey::Insert => [87.into_dart()].into_dart(),
            crate::api::syste::LddKey::KpReturn => [88.into_dart()].into_dart(),
            crate::api::syste::LddKey::KpMinus => [89.into_dart()].into_dart(),
            crate::api::syste::LddKey::KpPlus => [90.into_dart()].into_dart(),
            crate::api::syste::LddKey::KpMultiply => [91.into_dart()].into_dart(),
            crate::api::syste::LddKey::KpDivide => [92.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp0 => [93.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp1 => [94.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp2 => [95.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp3 => [96.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp4 => [97.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp5 => [98.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp6 => [99.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp7 => [100.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp8 => [101.into_dart()].into_dart(),
            crate::api::syste::LddKey::Kp9 => [102.into_dart()].into_dart(),
            crate::api::syste::LddKey::KpDelete => [103.into_dart()].into_dart(),
            crate::api::syste::LddKey::Function => [104.into_dart()].into_dart(),
            crate::api::syste::LddKey::Unknown(field0) => {
                [105.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for crate::api::syste::LddKey {}
impl flutter_rust_bridge::IntoIntoDart<crate::api::syste::LddKey> for crate::api::syste::LddKey {
    fn into_into_dart(self) -> crate::api::syste::LddKey {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::syste::LddKeyboardValue {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            crate::api::syste::LddKeyboardValue::ScanGunValue(field0, field1) => [
                0.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::syste::LddKeyboardValue::KeyboardValue(field0, field1) => [
                1.into_dart(),
                field0.into_into_dart().into_dart(),
                field1.into_into_dart().into_dart(),
            ]
            .into_dart(),
            crate::api::syste::LddKeyboardValue::ScanGunValueV2(field0) => {
                [2.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            crate::api::syste::LddKeyboardValue::KeyboardValueV2(field0) => {
                [3.into_dart(), field0.into_into_dart().into_dart()].into_dart()
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::syste::LddKeyboardValue
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::syste::LddKeyboardValue>
    for crate::api::syste::LddKeyboardValue
{
    fn into_into_dart(self) -> crate::api::syste::LddKeyboardValue {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<crate::api::syste::LddEvent, flutter_rust_bridge::for_generated::SseCodec>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::syste::LddKeyboardValue,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for u128 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.to_string(), serializer);
    }
}

impl SseEncode for f64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_f64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for i64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for crate::api::syste::LddButton {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::syste::LddButton::Left => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::syste::LddButton::Right => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::syste::LddButton::Middle => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::syste::LddButton::Unknown(field0) => {
                <i32>::sse_encode(3, serializer);
                <u8>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::syste::LddEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.name, serializer);
        <crate::api::syste::LddEventType>::sse_encode(self.event_type, serializer);
    }
}

impl SseEncode for crate::api::syste::LddEventType {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::syste::LddEventType::KeyPress(field0) => {
                <i32>::sse_encode(0, serializer);
                <crate::api::syste::LddKey>::sse_encode(field0, serializer);
            }
            crate::api::syste::LddEventType::KeyRelease(field0) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::syste::LddKey>::sse_encode(field0, serializer);
            }
            crate::api::syste::LddEventType::ButtonPress(field0) => {
                <i32>::sse_encode(2, serializer);
                <crate::api::syste::LddButton>::sse_encode(field0, serializer);
            }
            crate::api::syste::LddEventType::ButtonRelease(field0) => {
                <i32>::sse_encode(3, serializer);
                <crate::api::syste::LddButton>::sse_encode(field0, serializer);
            }
            crate::api::syste::LddEventType::MouseMove { x, y } => {
                <i32>::sse_encode(4, serializer);
                <f64>::sse_encode(x, serializer);
                <f64>::sse_encode(y, serializer);
            }
            crate::api::syste::LddEventType::Wheel { delta_x, delta_y } => {
                <i32>::sse_encode(5, serializer);
                <i64>::sse_encode(delta_x, serializer);
                <i64>::sse_encode(delta_y, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::syste::LddKey {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::syste::LddKey::Alt => {
                <i32>::sse_encode(0, serializer);
            }
            crate::api::syste::LddKey::AltGr => {
                <i32>::sse_encode(1, serializer);
            }
            crate::api::syste::LddKey::Backspace => {
                <i32>::sse_encode(2, serializer);
            }
            crate::api::syste::LddKey::CapsLock => {
                <i32>::sse_encode(3, serializer);
            }
            crate::api::syste::LddKey::ControlLeft => {
                <i32>::sse_encode(4, serializer);
            }
            crate::api::syste::LddKey::ControlRight => {
                <i32>::sse_encode(5, serializer);
            }
            crate::api::syste::LddKey::Delete => {
                <i32>::sse_encode(6, serializer);
            }
            crate::api::syste::LddKey::DownArrow => {
                <i32>::sse_encode(7, serializer);
            }
            crate::api::syste::LddKey::End => {
                <i32>::sse_encode(8, serializer);
            }
            crate::api::syste::LddKey::Escape => {
                <i32>::sse_encode(9, serializer);
            }
            crate::api::syste::LddKey::F1 => {
                <i32>::sse_encode(10, serializer);
            }
            crate::api::syste::LddKey::F10 => {
                <i32>::sse_encode(11, serializer);
            }
            crate::api::syste::LddKey::F11 => {
                <i32>::sse_encode(12, serializer);
            }
            crate::api::syste::LddKey::F12 => {
                <i32>::sse_encode(13, serializer);
            }
            crate::api::syste::LddKey::F2 => {
                <i32>::sse_encode(14, serializer);
            }
            crate::api::syste::LddKey::F3 => {
                <i32>::sse_encode(15, serializer);
            }
            crate::api::syste::LddKey::F4 => {
                <i32>::sse_encode(16, serializer);
            }
            crate::api::syste::LddKey::F5 => {
                <i32>::sse_encode(17, serializer);
            }
            crate::api::syste::LddKey::F6 => {
                <i32>::sse_encode(18, serializer);
            }
            crate::api::syste::LddKey::F7 => {
                <i32>::sse_encode(19, serializer);
            }
            crate::api::syste::LddKey::F8 => {
                <i32>::sse_encode(20, serializer);
            }
            crate::api::syste::LddKey::F9 => {
                <i32>::sse_encode(21, serializer);
            }
            crate::api::syste::LddKey::Home => {
                <i32>::sse_encode(22, serializer);
            }
            crate::api::syste::LddKey::LeftArrow => {
                <i32>::sse_encode(23, serializer);
            }
            crate::api::syste::LddKey::MetaLeft => {
                <i32>::sse_encode(24, serializer);
            }
            crate::api::syste::LddKey::MetaRight => {
                <i32>::sse_encode(25, serializer);
            }
            crate::api::syste::LddKey::PageDown => {
                <i32>::sse_encode(26, serializer);
            }
            crate::api::syste::LddKey::PageUp => {
                <i32>::sse_encode(27, serializer);
            }
            crate::api::syste::LddKey::Return => {
                <i32>::sse_encode(28, serializer);
            }
            crate::api::syste::LddKey::RightArrow => {
                <i32>::sse_encode(29, serializer);
            }
            crate::api::syste::LddKey::ShiftLeft => {
                <i32>::sse_encode(30, serializer);
            }
            crate::api::syste::LddKey::ShiftRight => {
                <i32>::sse_encode(31, serializer);
            }
            crate::api::syste::LddKey::Space => {
                <i32>::sse_encode(32, serializer);
            }
            crate::api::syste::LddKey::Tab => {
                <i32>::sse_encode(33, serializer);
            }
            crate::api::syste::LddKey::UpArrow => {
                <i32>::sse_encode(34, serializer);
            }
            crate::api::syste::LddKey::PrintScreen => {
                <i32>::sse_encode(35, serializer);
            }
            crate::api::syste::LddKey::ScrollLock => {
                <i32>::sse_encode(36, serializer);
            }
            crate::api::syste::LddKey::Pause => {
                <i32>::sse_encode(37, serializer);
            }
            crate::api::syste::LddKey::NumLock => {
                <i32>::sse_encode(38, serializer);
            }
            crate::api::syste::LddKey::BackQuote => {
                <i32>::sse_encode(39, serializer);
            }
            crate::api::syste::LddKey::Num1 => {
                <i32>::sse_encode(40, serializer);
            }
            crate::api::syste::LddKey::Num2 => {
                <i32>::sse_encode(41, serializer);
            }
            crate::api::syste::LddKey::Num3 => {
                <i32>::sse_encode(42, serializer);
            }
            crate::api::syste::LddKey::Num4 => {
                <i32>::sse_encode(43, serializer);
            }
            crate::api::syste::LddKey::Num5 => {
                <i32>::sse_encode(44, serializer);
            }
            crate::api::syste::LddKey::Num6 => {
                <i32>::sse_encode(45, serializer);
            }
            crate::api::syste::LddKey::Num7 => {
                <i32>::sse_encode(46, serializer);
            }
            crate::api::syste::LddKey::Num8 => {
                <i32>::sse_encode(47, serializer);
            }
            crate::api::syste::LddKey::Num9 => {
                <i32>::sse_encode(48, serializer);
            }
            crate::api::syste::LddKey::Num0 => {
                <i32>::sse_encode(49, serializer);
            }
            crate::api::syste::LddKey::Minus => {
                <i32>::sse_encode(50, serializer);
            }
            crate::api::syste::LddKey::Equal => {
                <i32>::sse_encode(51, serializer);
            }
            crate::api::syste::LddKey::KeyQ => {
                <i32>::sse_encode(52, serializer);
            }
            crate::api::syste::LddKey::KeyW => {
                <i32>::sse_encode(53, serializer);
            }
            crate::api::syste::LddKey::KeyE => {
                <i32>::sse_encode(54, serializer);
            }
            crate::api::syste::LddKey::KeyR => {
                <i32>::sse_encode(55, serializer);
            }
            crate::api::syste::LddKey::KeyT => {
                <i32>::sse_encode(56, serializer);
            }
            crate::api::syste::LddKey::KeyY => {
                <i32>::sse_encode(57, serializer);
            }
            crate::api::syste::LddKey::KeyU => {
                <i32>::sse_encode(58, serializer);
            }
            crate::api::syste::LddKey::KeyI => {
                <i32>::sse_encode(59, serializer);
            }
            crate::api::syste::LddKey::KeyO => {
                <i32>::sse_encode(60, serializer);
            }
            crate::api::syste::LddKey::KeyP => {
                <i32>::sse_encode(61, serializer);
            }
            crate::api::syste::LddKey::LeftBracket => {
                <i32>::sse_encode(62, serializer);
            }
            crate::api::syste::LddKey::RightBracket => {
                <i32>::sse_encode(63, serializer);
            }
            crate::api::syste::LddKey::KeyA => {
                <i32>::sse_encode(64, serializer);
            }
            crate::api::syste::LddKey::KeyS => {
                <i32>::sse_encode(65, serializer);
            }
            crate::api::syste::LddKey::KeyD => {
                <i32>::sse_encode(66, serializer);
            }
            crate::api::syste::LddKey::KeyF => {
                <i32>::sse_encode(67, serializer);
            }
            crate::api::syste::LddKey::KeyG => {
                <i32>::sse_encode(68, serializer);
            }
            crate::api::syste::LddKey::KeyH => {
                <i32>::sse_encode(69, serializer);
            }
            crate::api::syste::LddKey::KeyJ => {
                <i32>::sse_encode(70, serializer);
            }
            crate::api::syste::LddKey::KeyK => {
                <i32>::sse_encode(71, serializer);
            }
            crate::api::syste::LddKey::KeyL => {
                <i32>::sse_encode(72, serializer);
            }
            crate::api::syste::LddKey::SemiColon => {
                <i32>::sse_encode(73, serializer);
            }
            crate::api::syste::LddKey::Quote => {
                <i32>::sse_encode(74, serializer);
            }
            crate::api::syste::LddKey::BackSlash => {
                <i32>::sse_encode(75, serializer);
            }
            crate::api::syste::LddKey::IntlBackslash => {
                <i32>::sse_encode(76, serializer);
            }
            crate::api::syste::LddKey::KeyZ => {
                <i32>::sse_encode(77, serializer);
            }
            crate::api::syste::LddKey::KeyX => {
                <i32>::sse_encode(78, serializer);
            }
            crate::api::syste::LddKey::KeyC => {
                <i32>::sse_encode(79, serializer);
            }
            crate::api::syste::LddKey::KeyV => {
                <i32>::sse_encode(80, serializer);
            }
            crate::api::syste::LddKey::KeyB => {
                <i32>::sse_encode(81, serializer);
            }
            crate::api::syste::LddKey::KeyN => {
                <i32>::sse_encode(82, serializer);
            }
            crate::api::syste::LddKey::KeyM => {
                <i32>::sse_encode(83, serializer);
            }
            crate::api::syste::LddKey::Comma => {
                <i32>::sse_encode(84, serializer);
            }
            crate::api::syste::LddKey::Dot => {
                <i32>::sse_encode(85, serializer);
            }
            crate::api::syste::LddKey::Slash => {
                <i32>::sse_encode(86, serializer);
            }
            crate::api::syste::LddKey::Insert => {
                <i32>::sse_encode(87, serializer);
            }
            crate::api::syste::LddKey::KpReturn => {
                <i32>::sse_encode(88, serializer);
            }
            crate::api::syste::LddKey::KpMinus => {
                <i32>::sse_encode(89, serializer);
            }
            crate::api::syste::LddKey::KpPlus => {
                <i32>::sse_encode(90, serializer);
            }
            crate::api::syste::LddKey::KpMultiply => {
                <i32>::sse_encode(91, serializer);
            }
            crate::api::syste::LddKey::KpDivide => {
                <i32>::sse_encode(92, serializer);
            }
            crate::api::syste::LddKey::Kp0 => {
                <i32>::sse_encode(93, serializer);
            }
            crate::api::syste::LddKey::Kp1 => {
                <i32>::sse_encode(94, serializer);
            }
            crate::api::syste::LddKey::Kp2 => {
                <i32>::sse_encode(95, serializer);
            }
            crate::api::syste::LddKey::Kp3 => {
                <i32>::sse_encode(96, serializer);
            }
            crate::api::syste::LddKey::Kp4 => {
                <i32>::sse_encode(97, serializer);
            }
            crate::api::syste::LddKey::Kp5 => {
                <i32>::sse_encode(98, serializer);
            }
            crate::api::syste::LddKey::Kp6 => {
                <i32>::sse_encode(99, serializer);
            }
            crate::api::syste::LddKey::Kp7 => {
                <i32>::sse_encode(100, serializer);
            }
            crate::api::syste::LddKey::Kp8 => {
                <i32>::sse_encode(101, serializer);
            }
            crate::api::syste::LddKey::Kp9 => {
                <i32>::sse_encode(102, serializer);
            }
            crate::api::syste::LddKey::KpDelete => {
                <i32>::sse_encode(103, serializer);
            }
            crate::api::syste::LddKey::Function => {
                <i32>::sse_encode(104, serializer);
            }
            crate::api::syste::LddKey::Unknown(field0) => {
                <i32>::sse_encode(105, serializer);
                <u32>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for crate::api::syste::LddKeyboardValue {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        match self {
            crate::api::syste::LddKeyboardValue::ScanGunValue(field0, field1) => {
                <i32>::sse_encode(0, serializer);
                <String>::sse_encode(field0, serializer);
                <u128>::sse_encode(field1, serializer);
            }
            crate::api::syste::LddKeyboardValue::KeyboardValue(field0, field1) => {
                <i32>::sse_encode(1, serializer);
                <crate::api::syste::LddEvent>::sse_encode(field0, serializer);
                <u128>::sse_encode(field1, serializer);
            }
            crate::api::syste::LddKeyboardValue::ScanGunValueV2(field0) => {
                <i32>::sse_encode(2, serializer);
                <Vec<crate::api::syste::LddEvent>>::sse_encode(field0, serializer);
            }
            crate::api::syste::LddKeyboardValue::KeyboardValueV2(field0) => {
                <i32>::sse_encode(3, serializer);
                <crate::api::syste::LddEvent>::sse_encode(field0, serializer);
            }
            _ => {
                unimplemented!("");
            }
        }
    }
}

impl SseEncode for Vec<crate::api::syste::LddEvent> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::syste::LddEvent>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<usize> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <usize>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // Generated by `flutter_rust_bridge`@ 2.3.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // Generated by `flutter_rust_bridge`@ 2.3.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
