// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/syste.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<LddEvent> dco_decode_StreamSink_ldd_event_Sse(dynamic raw);

  @protected
  RustStreamSink<LddKeyboardValue> dco_decode_StreamSink_ldd_keyboard_value_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  BigInt dco_decode_U128(dynamic raw);

  @protected
  LddButton dco_decode_box_autoadd_ldd_button(dynamic raw);

  @protected
  LddEvent dco_decode_box_autoadd_ldd_event(dynamic raw);

  @protected
  LddKey dco_decode_box_autoadd_ldd_key(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_usize(dynamic raw);

  @protected
  double dco_decode_f_64(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  LddButton dco_decode_ldd_button(dynamic raw);

  @protected
  LddEvent dco_decode_ldd_event(dynamic raw);

  @protected
  LddEventType dco_decode_ldd_event_type(dynamic raw);

  @protected
  LddKey dco_decode_ldd_key(dynamic raw);

  @protected
  LddKeyboardValue dco_decode_ldd_keyboard_value(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_usize(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<LddEvent> sse_decode_StreamSink_ldd_event_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<LddKeyboardValue> sse_decode_StreamSink_ldd_keyboard_value_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_U128(SseDeserializer deserializer);

  @protected
  LddButton sse_decode_box_autoadd_ldd_button(SseDeserializer deserializer);

  @protected
  LddEvent sse_decode_box_autoadd_ldd_event(SseDeserializer deserializer);

  @protected
  LddKey sse_decode_box_autoadd_ldd_key(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  double sse_decode_f_64(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  LddButton sse_decode_ldd_button(SseDeserializer deserializer);

  @protected
  LddEvent sse_decode_ldd_event(SseDeserializer deserializer);

  @protected
  LddEventType sse_decode_ldd_event_type(SseDeserializer deserializer);

  @protected
  LddKey sse_decode_ldd_key(SseDeserializer deserializer);

  @protected
  LddKeyboardValue sse_decode_ldd_keyboard_value(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_ldd_event_Sse(
      RustStreamSink<LddEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_ldd_keyboard_value_Sse(
      RustStreamSink<LddKeyboardValue> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_U128(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ldd_button(
      LddButton self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ldd_event(
      LddEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ldd_key(LddKey self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_button(LddButton self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_event(LddEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_event_type(LddEventType self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_key(LddKey self, SseSerializer serializer);

  @protected
  void sse_encode_ldd_keyboard_value(
      LddKeyboardValue self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_usize(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  RustLibWire.fromExternalLibrary(ExternalLibrary lib);
}

@JS('wasm_bindgen')
external RustLibWasmModule get wasmModule;

@JS()
@anonymous
extension type RustLibWasmModule._(JSObject _) implements JSObject {}
